spring:
  application:
    name: library-api

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  cache:
    type: redis
    redis:
      time-to-live: 10m

file:
  storage:
    path: uploads/books

  upload:
    max-size: 5MB
    allowed-types:
      .pdf: application/pdf
      .epub: application/epub+zip

  cleanup:
    cron: "0 0 2 * * *"

async:
  executor:
    core-pool-size: 2
    max-pool-size: 5
    queue-capacity: 100
    thread-name-prefix: library-async-